# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pagy` gem.
# Please instead update this file by running `bin/tapioca gem pagy`.

# Core class
class Pagy
  # Merge and validate the options, do some simple arithmetic and set the instance variables
  #
  # @raise [OverflowError]
  # @return [Pagy] a new instance of Pagy
  def initialize(vars); end

  # Returns the value of attribute count.
  def count; end

  # Returns the value of attribute from.
  def from; end

  # Returns the value of attribute in.
  def in; end

  # Returns the value of attribute items.
  def items; end

  # Allow the customization of the output (overridden by the calendar extra)
  def label; end

  # Allow the customization of the output (overridden by the calendar extra)
  def label_for(page); end

  # Returns the value of attribute last.
  def last; end

  # Returns the value of attribute next.
  def next; end

  # Returns the value of attribute offset.
  def offset; end

  # Returns the value of attribute page.
  def page; end

  # Returns the value of attribute pages.
  def pages; end

  # Returns the value of attribute params.
  def params; end

  # Returns the value of attribute prev.
  def prev; end

  # Return the array of page numbers and :gap items e.g. [1, :gap, 7, 8, "9", 10, 11, :gap, 36]
  #
  # @raise [VariableError]
  def series(size: T.unsafe(nil), **_); end

  # Returns the value of attribute to.
  def to; end

  # Returns the value of attribute vars.
  def vars; end

  protected

  # Apply defaults, cleanup blanks and set @vars
  def normalize_vars(vars); end

  # Setup @items (overridden by the gearbox extra)
  def setup_items_var; end

  # Setup @offset based on the :gearbox_items variable
  def setup_offset_var; end

  # Setup @pages and @last (overridden by the gearbox extra)
  def setup_pages_var; end

  # Setup and validate @params
  #
  # @raise [VariableError]
  def setup_params_var; end

  # Setup and validates the passed vars: var must be present and value.to_i must be >= to min
  def setup_vars(name_min); end

  class << self
    # Root pathname to get the path of Pagy files like templates or dictionaries
    def root; end
  end
end

# Define a dummy params method if it's not already defined in the including module
module Pagy::Backend
  private

  # Return Pagy object and paginated items/results
  def pagy(collection, vars = T.unsafe(nil)); end

  # Sub-method called only by #pagy: here for easy customization of record-extraction by overriding
  # You may need to override this method for collections without offset|limit
  def pagy_get_items(collection, pagy); end

  # Sub-method called only by #pagy: here for easy customization of variables by overriding
  # You may need to override the count call for non AR collections
  def pagy_get_vars(collection, vars); end
end

# Default core vars: constant for easy access, but mutable for customizable defaults
Pagy::DEFAULT = T.let(T.unsafe(nil), Hash)

# Frontend modules are specially optimized for performance.
# The resulting code may not look very elegant, but produces the best benchmarks
module Pagy::Frontend
  include ::Pagy::UrlHelpers

  # Return examples: "Displaying items 41-60 of 324 in total" or "Displaying Products 41-60 of 324 in total"
  def pagy_info(pagy, pagy_id: T.unsafe(nil), item_name: T.unsafe(nil), i18n_key: T.unsafe(nil)); end

  # Return a performance optimized proc to generate the HTML links
  # Benchmarked on a 20 link nav: it is ~22x faster and uses ~18x less memory than rails' link_to
  def pagy_link_proc(pagy, link_extra: T.unsafe(nil)); end

  # Generic pagination: it returns the html with the series of links to the pages
  def pagy_nav(pagy, pagy_id: T.unsafe(nil), link_extra: T.unsafe(nil), **vars); end

  # Similar to I18n.t: just ~18x faster using ~10x less memory
  # (@pagy_locale explicitly initialized in order to avoid warning)
  def pagy_t(key, opts = T.unsafe(nil)); end
end

# Pagy i18n implementation, compatible with the I18n gem, just a lot faster and lighter
module Pagy::I18n
  extend ::Pagy::I18n

  # Public method to configure the locales: overrides the default, build the DATA and freezes it
  def load(*locales); end

  # Translate and pluralize the key with the locale DATA
  def t(locale, key, opts = T.unsafe(nil)); end

  # Translate and pluralize the key with the locale DATA
  def translate(locale, key, opts = T.unsafe(nil)); end

  private

  # Build the DATA hash out of the passed locales
  def build(*locales); end

  # Create a flat hash with dotted notation keys
  def flatten(initial, prefix = T.unsafe(nil)); end
end

# Stores the i18n DATA structure for each loaded locale
# default on the first locale DATA
Pagy::I18n::DATA = T.let(T.unsafe(nil), Hash)

# Pluralization rules
module Pagy::I18n::P11n; end

# Store the RULE to apply to each LOCALE
# the :one_other RULE is the default for locales missing from this list
Pagy::I18n::P11n::LOCALE = T.let(T.unsafe(nil), Hash)

# Store the proc defining each pluralization RULE
# Logic adapted from https://github.com/svenfuchs/rails-i18n
Pagy::I18n::P11n::RULE = T.let(T.unsafe(nil), Hash)

# I18n configuration error
class Pagy::I18nError < ::StandardError; end

# Generic internal error
class Pagy::InternalError < ::StandardError; end

Pagy::LABEL_PLACEHOLDER = T.let(T.unsafe(nil), String)

# Specific overflow error
class Pagy::OverflowError < ::Pagy::VariableError; end

# Used for search and replace, hardcoded also in the pagy.js file
Pagy::PAGE_PLACEHOLDER = T.let(T.unsafe(nil), String)

# Provide the helpers to handle the url in frontend and backend
module Pagy::UrlHelpers
  # Return the URL for the page, relying on the params method and Rack by default.
  # It supports all Rack-based frameworks (Sinatra, Padrino, Rails, ...).
  # For non-rack environments you can use the standalone extra
  def pagy_url_for(pagy, page, absolute: T.unsafe(nil), html_escaped: T.unsafe(nil)); end

  private

  # Transitional code to handle params deprecations. It will be removed in version 6.0
  def pagy_deprecated_params(pagy, params); end
end

Pagy::VERSION = T.let(T.unsafe(nil), String)

# Generic variable error
class Pagy::VariableError < ::ArgumentError
  # Set the variables and prepare the message
  #
  # @return [VariableError] a new instance of VariableError
  def initialize(pagy, variable, description, value); end

  # Returns the value of attribute pagy.
  def pagy; end

  # Returns the value of attribute value.
  def value; end

  # Returns the value of attribute variable.
  def variable; end
end
