version: "3"

services:
  postgres:
    image: postgis/postgis:14-3.2
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  # redis:
  #   image: redis:7
  #   ports:
  #     - 6379:6379

volumes:
  postgres: null
