# See https://github.com/Shopify/tapioca
gem:
  doc: true
  exclude:
    - prettier
    - rbi
    - rubocop-graphql
    - rubocop-rails
    - rubocop-shopify
    - rubocop-sorbet
    - sassc-rails
    - spoom
    - tapioca
    - tilt
    - yard
    - yard-sorbet
