# See https://github.com/Shopify/tapioca

gem:
  doc: true
  exclude:
    - prettier
    - pry
    - pry-rails
    - rake
    - rubocop-graphql
    - rubocop-rails
    - rubocop-shopify
    - rubocop-sorbet
    - sassc
    - sassc-rails
    - spoom
    - tapioca
    - thor
    - tilt
    - yard
    - yard-sorbet
