# See https://github.com/Shopify/tapioca

gem:
  doc: true
  exclude:
    - annotate
    - pry
    - pry-rails
    - rake
    - rubocop-rails
    - rubocop-shopify
    - rubocop-sorbet
    - thor
    - yard
    - yard-sorbet
    - tapioca
    - spoom
    - prettier
